### ISSUE TITLE
Topology Namespaces don't include their public key information

### ISSUE THREAD

**Issue by turetske** [PelicanPlatform/pelican#1029]
Pelican Service:
- [x ] Registry
**Is your feature request related to a problem? Please describe.**

The pelican registry cannot get public keys for namespaces registered with Topology. When getNamespaceJwksByPrefix is run, it will return a "namespace with prefix %q not fount in database" error because it doesn't check topology. The reason it doesn't check topology is because topology doesn't contain any public key information.

**Describe the solution you'd like**

This needs to be fixed in some way. The information in Topology has auth and non-auth endpoints, but the public key location is not clear. There are two options for a solution depending on whether the public key information for topology namespaces is available and it uses jwks for authentication or if there is a different way to do so.

If a public key is available:

   1. When the director queries topology for its information and creates OriginAds, make sure the public key information is included.
   2. Alter the Topology table to include the public key information
   3. Alter the getNamespaceJwksByPrefix function to check topology for the prefix before checking the namespace table

If a different authentication/authorization method is used:
    1. Store that authentication method in the the originAds
    2. Alter the topology table to include the needed information
    3. Anything that uses the getNamespaceJwksByPrefix needs to check if the namespace is from Topology and, if so, implement the other auth schema for verification with topology namespaces

**Comment by haoming29** [comment]
According to @brianhlin, OSDF origins have a shared issuer/public jwks which live at https://osg-htc.org/osdf/.well-known/openid-configuration and
https://osg-htc.org/osdf/public_signing_key.jwks

So the initial step we can take is to cache the public key into a registry TTL cache, and return that key if the namespace is from topology in `getNamespaceJwksByPrefix`.

I do notice that the above jwks contains two keys, but Pelican does not support that yet. Not sure how to proceed with this setup.

**Comment by brianhlin** [comment]
To be clear, there are multiple public issuers -- one for each organization. For example, CHTC has its own issuer that is separate from the OSPool issuer. Each of them can and often do have mutliple keys as you note.

**Comment by haoming29** [comment]
> To be clear, there are multiple public issuers -- one for each organization. For example, CHTC has its own issuer that is separate from the OSPool issuer. Each of them can and often do have mutliple keys as you note.

In that case, it would be difficult for Pelican to be compatible with topology namespaces, as there needs to be a way for Pelican to look up the public key associated with the namespace

**Comment by haoming29** [comment]
So I see there are a couple things Pelican needs to be done before we can at least treat namespaces from the topology the same as Pelican namespace (so that Pelican namespace can start replace the topology namespace):

* Allow the same namespace prefix to be present at both topology and pelican namespace. As @jhiemstrawisc noted, we need to have namespace registered at both sides to allow legacy OSDF cache to serve Pelican origin
* Related to point 1, Pelican registry key chaining check should allow a Pelican namespace to be registered under a topology namespace (as a sub namespace). Example: given a `/chtc` namespace from topology, Pelican admin should be able to register `/chtc/foo`. How we manage the security check is a separate topic. Currently we simply deny such registration
* Pelican registry should be able to provide the public jwks by namespace prefix look up for namespace from the topology (so that downstream calls to get jwks for keychaining check and so on can work)
* Accept multiple keys in a jwks and always look up a key by kid (given that jwks from the topology can and do contain multiple keys)

We should bring this up in this week's Pelican dev meeting. There are a bunch of decision to make regarding those questions

**Comment by brianhlin** [comment]
@haoming29 I just realize that I gave you the wrong links regarding the public keys. Using `/ospool/PROTECTED` again, we use https://osg-htc.org/ospool as specified here https://github.com/opensciencegrid/topology/blob/master/virtual-organizations/OSG.yaml#L134. You can of course find the relevant bits in the `.well-known/openid-configuration` location.

**Comment by haoming29** [comment]
As we discussed in the stand up meeting on 4/3, we decided to proceed with the solution that allows registration of the namespaces that's a sub namespace of the existing topology namespaces. We also want to advocate to the admins to register the namespace through the registry web UI (with CILogon) for identity verification. However, we still need to figure out the duplicated key situation and how we should handle them.
