### ISSUE TITLE
Improve "site name" handling

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#1106]
The "site name" is currently a fairly nebulous concept.  Let's start fixing up semantics.

0. The site name should not be required for a prefix registration.  It should be required for the cache registration - and we'll have an origin registration in the future - but there's not much point for the prefix.
1. If the "site name" is not set in the configuration - but it is filled in in the cache or (in the future) origin registration - use that.
2.  In "pelican mode", the "site name" should default to the hostname in the external web URL, not the result of `os.Hostname`.  This should be a more sane default in container-based systems.
3. In "OSDF mode", the registration page should provide a drop-down populated with existing OSDF site names.

**Comment by haoming29** [comment]
A couple of road blockers I found when implementing this:
* We need to have #1107 ASAP; otherwise, with multi-export support at the origin, we can't wisely determine which namespace to fetch the site name from the registry. Currently we only grab the first exported namespace and use that, which is a bit sketchy.
*  We need to add an extra `serverAd` field `Hostname` to the director (and during advertisement), with this change. When I took this approach and apply it on cache, the director fails to verify the advertisement token from the cache because it relies on the site name (or `Name` from the server ad) to find the namespace for the cache and grab the public jwks from the registry. If the `Name` is different from the hostname of the cache (which is used to register the namespace for the cache at the registry), the registry won't be able to find the namespace registration for the cache.
