### ISSUE TITLE
Custom Field name results in edgecase

### ISSUE THREAD

**Issue by CannonLock** [PelicanPlatform/pelican#1158]
We currently provide the UI with the cache/namespace fields with the following api response:

```
{
    "name": "custom_fields.Boolean Field",
    "displayed_name": "Boolean Field",
    "type": "bool",
    "required": true,
    "options": [],
    "description": "Cool Boolean Description Required"
}
```

I am expected to POST/PATCH this via:

```
{
    custom_fields:
        "Boolean Field": <value>
}
```

Which begs the question what if I use `Boolean.Field` as my field name?

My preference is to get rid of the nesting and just check for name collisions. Easiest solution is likely escaping the . when you send them to me so I know what ones are distinguishing object structure and what ones are part of the name.

**Comment by CannonLock** [comment]
Actually, if I operate on the assumption that custom_fields will never be nested more then once I can determine the correct nesting. 

I will keep this open because I am curious your thoughts as personally that feels a little dirty.

**Comment by CannonLock** [comment]
I finished the UI for this so lets keep it as is for now. Lets note for the future though.

**Comment by haoming29** [comment]
First thing that I spotted is that `"custom_fields.Boolean Field"` is not a valid field name, nor `Boolean.Field` (but apparently I didn't check this in the code 😞, so this ticket can be a good place to enforce such rules), the filed name must be sneak case so that the `displayed_name` can be correctly converted
For the dot notation, I don't think we will support nested custom fields in the near future. The dot in the name was to distinguish between `admin_metadata` and `custom_fields` as they are both parent structure holding the fields.

**Comment by haoming29** [comment]
oops, nvm I can open a new ticket for what I mentioned above
