### ISSUE TITLE
Write design doc for XRootd CORS Headers for web based access

### ISSUE THREAD

**Issue by CannonLock** [PelicanPlatform/pelican#1217]
Write a design document for auth'd and non auth'd access to resources from the web.

**Comment by CannonLock** [comment]
https://docs.google.com/document/d/1iFS56Wjg70WNO0Qsph2rgLTwXfhM8MlFKOe4P0qadrk/edit#heading=h.d17j0pe79uiy

**Comment by CannonLock** [comment]
![web-client-01](https://github.com/PelicanPlatform/pelican/assets/49032265/a296b3a0-2191-43d2-b0ec-c7ab8e6f9a98)

**Comment by bbockelm** [comment]
Thanks for the writeup!  Thoughts:

1.  Should we set `Access-Control-Allow-Origin: *` in the response from the origin/cache _or_ should we do something more targeted, such as `Access-Control-Allow-Origin: https://director.example.com:8443`?
      - Right now, there's no way to set extra headers on XRootD responses.  This would require a patch -- but I think it's a pretty modest patch to add a static header in the configuration.
3. XRootD has a plugin interface that can hijack an entire HTTP verb, meaning we can do a custom plugin for handling all of the `OPTIONS` queries.  So no XRootD patches patches are necessary for that part to work, just Yet Another C++ plugin we'll need to ship.
4. Instead of adding the `redirect=false` query parameter, should we just add an API specifically for the web client?  If not, what should the HTTP status code be?  204?

**Comment by CannonLock** [comment]
1. * is needed if we ever want to have a cache respond to a non director web page. For instance if we want a single page to show multiple federations.

3. We went back and forth on it, I would be happy with /metadata/<namespace>/<file> returning the information as a JSON. We decided on the no redirect because it was closest to the existing implementation, reducing complexity. If we want a nicer way to get this information in the future the JSON is better, otherwise I prefer the no redirect. 204 is sound for the response code.
