### ISSUE TITLE
Origin should report storage type to the director in its advertisement

### ISSUE THREAD

**Issue by haoming29** [PelicanPlatform/pelican#1386]
For non-POSIX origins, we can't upload files to the origin, thus give us 403 errors when doing so at the director file tests. Let's report the storage type from the origin to the director and skip issuing director tests to that origin if it's not in POSIX, and document the reason why the test is off in various places (prometheus, server log, etc)

**Comment by bbockelm** [comment]
I wanted to slightly disagree here.

We should report the storage type to the director because it's an important statistics we should aggregate.  For example, when counting the number of origins in prometheus, this is a label we should use.

However, if the origin knows it cannot support director tests, it should explicitly state this in the ad instead of trying to have the director guess/infer this from other properties.  For example, the NCAR origin cannot do director tests but is POSIX.

**Comment by bbockelm** [comment]
Yes, I think that's right!
