### ISSUE TITLE
Wrong key for aggregating namespaces under the same origin for topology servers

### ISSUE THREAD

**Issue by haoming29** [PelicanPlatform/pelican#1406]
In https://github.com/PelicanPlatform/pelican/blob/main/director/advertise.go#L238 , we are aggregating the namespaces under the same origin/cache servers, but we used `serverAd` as the unique key for the server. This will cause wrong aggregation result as `serverAd` can be different for the same origin, if the namespaces it exports have different capabilities. Take ap20 origin as an example, it exports two namespaces, `/ospool/ap20/data` and `/ospool/ap20/.well-known`. Below is the topology json for the two namespaces:

* `/ospool/ap20/data`: 
```json
{
    "caches": [...], // entries skipped for readability
    "credential_generation": {
        "base_path": null,
        "issuer": "https://osg-htc.org/ospool",
        "max_scope_depth": 4,
        "strategy": "OAuth2",
        "vault_issuer": null,
        "vault_server": null
    },
    "dirlisthost": null,
    "origins": [
        {
            "auth_endpoint": "ap20.uc.osg-htc.org:1095",
            "endpoint": "ap20.uc.osg-htc.org:1094",
            "production": true,
            "resource": "UChicago_OSGConnect_ap20"
        }
    ],
    "path": "/ospool/ap20/data",
    "readhttps": true,
    "scitokens": [
        {
            "base_path": [
                "/ospool/ap20"
            ],
            "issuer": "https://ap20.uc.osg-htc.org:1094/ospool/ap20",
            "restricted_path": []
        }
    ],
    "usetokenonread": true,
    "writebackhost": "https://ap20.uc.osg-htc.org:1095"
}
```

* `/ospool/ap20/.well-known`:
```json
{
    "caches": [],
    "credential_generation": null,
    "dirlisthost": null,
    "origins": [
        {
            "auth_endpoint": "ap20.uc.osg-htc.org:1095",
            "endpoint": "ap20.uc.osg-htc.org:1094",
            "production": true,
            "resource": "UChicago_OSGConnect_ap20"
        }
    ],
    "path": "/ospool/ap20/.well-known",
    "readhttps": false,
    "scitokens": [],
    "usetokenonread": false,
    "writebackhost": null
}
```

Notice that although both namespaces have the exact same `origin` field, they differ in the capabilities and issuer, and we parse the two entries into `serverAd`, the result will be different too. Causing duplicated entries.

To fix the issue, we should 
1.Always sort the `namespace` filed from topology json by `path` field to make sure we are getting stable result
2.Come up with a mechanism for identifying same origin exporting multiple namespaces and "correctly" parse the origin `serverAd`. In this case, we shouldn't use the information from `/ospool/ap20/.well-known` for the ap20 origin but from `/ospool/ap20/data`, as it provides the correct issuer and auth information.

**Comment by haoming29** [comment]
@bbockelm For the second point in fixing the issue, I can't think of a good mechanism on top of my head. Do we want to have a custom "compare" function to compare on `serverAd` and whoever has more information should win?

**Comment by bbockelm** [comment]
Here's my idea for the second item:
1. In `AdvertiseOSDF`, we currently create a map `map[server_structs.ServerAd][]server_structs.NamespaceAdV2` for origins (`originAdMap`).  Change this to `map[string]struct{server_structs.ServerAd, []server_structs.NamespaceAdV2}` where the key of the map is the URL of the service and the value is the current origin ad and the list of namespace ads.
2. Update `parseServerAdFromTopology` to take in the previous copy of the `ServerAd` for the URL and apply the union of all capabilities.
   - Since the things the origin is willing to do and the things the namespace is willing to do should be intersected, this won't ad any new capabilities to the namespace.
4. In the for loop on `namespaces.Namespaces`, pass the existing version of the `ServerAd` in the `originAdMap` to `parseServerAdFromTopology`, aggregating capabilities.
5. When invoking `recordAd`, loop through `originAdMap`.  Ignore the keys and pass the value (the constructed `ServerAd` and the namespace ads) to the function.

**Comment by haoming29** [comment]
Trying to understand the idea of union here. Is it safe to say we are taking "more permissive" permission at the origin level? Say if a namespace allows public read but the other one doesn't, the origin should allow public read. Similarly for other capabilities.

**Comment by bbockelm** [comment]
That's correct.

The server ad should be "what the origin is willing to do" while the namespace ad is "what the namespace owner is willing to do".  The actual configuration / response from the redirector should be the combination of both.
