### ISSUE TITLE
object delete

### ISSUE THREAD

**Issue by rynge** [PelicanPlatform/pelican#1685]
Pelican Service:
- [X] Client
- [ ] Plugin
- [ ] Registry
- [ ] Director
- [X] Origin
- [ ] Cache
- [ ] Other (please give the detail)

Maybe already discussed, but I would love to see an `pelican object delete` implemented. We sometimes use Pelican for intermediate data during a workflow run, and the workflow can cleanup as it goes. Currently we are copying 0-byte files to free up disk space at the origin - a real `delete` would be much cleaner.

**Comment by jhiemstrawisc** [comment]
After some developer discussion, we think we can support this request in a limited form. There's some complexity because one might expect that an `object delete/rm` command should delete the object from both caches an origins. We can support deleting from origins, but not from caches at this point.

Due to this limitation, we think we'll create the tool but hide it from the CLI by default, so you'll only be able to use it if you know it exists and you understand the consequences of changing something at the origin without changing it at caches.
