### ISSUE TITLE
Add "ServerType" as a globally accessible config

### ISSUE THREAD

**Issue by haoming29** [PelicanPlatform/pelican#280]
When implementing #174, I have to distinguish between "director" and other server types in order to pass special Prometheus config to the director server. With what we have now, it requires passing some argument all the way from `web_ui.GetEngine` to `web_ui.ConfigureEmbeddedPrometheus` which is a very long chain. This is inefficient and confuses people. The workaround for this is to obtain caller name from `GetEngine` to save the top-level server type argument, but this still requires 3+ layers of argument passing.

I propose that we create either a viper config value or a global variable like `ServerType` that can be only set once like in here: https://github.com/PelicanPlatform/pelican/blob/00bc6327159f178d5866b92a002558e29bd94419/config/config.go#L95

when we start the server `cmd/serveXXX()` (i.e. `serveDirector()`), so that we can know which server type is running now.

**Comment by bbockelm** [comment]
Agreed that this is a bit of a mess.  However, I'd like to preserve the future ability to have multiple daemon types all running inside a single process.

So, instead of a single value, how about a type like this:

```
type ServerComponent int

func (component ServerComponent) Set(ServerComponent newComp) {
    component |= newComp
}

func (component ServerComponent) IsEnabled(ServerComponent testComp) bool {
    return (component & testComp) == testComp
}

const (
   ComponentOrigin ServerComponent = 1
   ComponentDirector ServerComponent = 2
   ComponentRegistry ServerComponent = 4
)
```

(typing this outside a golang compiler so I'm not checking correctness -- hopefully the pseudocode above makes sense)

With this, we could refactor the different components to have a single startup function.  The implementation of `pelican origin serve` would simply be setting the `ComponentOrigin` flag inside the config then calling the common startup function.  This way, one could enable other components through configuration to implement #172.

**Comment by haoming29** [comment]
> @haoming29 , I know we now initialize servers by passing a ServerType (I think I saw Brian refactor this into an interface a few days ago). Does that change close this issue?

That's good to know! A quick peek at the main branch and I think we should be good to close this issue.
