### ISSUE TITLE
Add LoadDirectorPublicKey to integration test

### ISSUE THREAD

**Issue by haoming29** [PelicanPlatform/pelican#281]
As mentioned here https://github.com/PelicanPlatform/pelican/pull/254#issuecomment-1777828049, we want to test the newly added `LoadDirectorPublicKey` but we can't do it with unit testing as it requires sending nested HTTP requests to director. Therefore, we should move the testing to integration test when we have built our integration test infrastructure.

Ref #170

**Comment by joereuss12** [comment]
After talking with Haoming about this issue, it seems like we might need to improve our end-to-end and integration test infrastructure before moving forward with this test. I could be wrong though, just might need a little more assistance at a later date but since this is not a super pressing issue (since it seems to work) and might take a while to develop, I am going to move this to the 7.4.0 milestone.

**Comment by haoming29** [comment]
`LoadDirectorPublicKey` will be removed in #572 due to changes in the federation architecture where director will be a federation. Therefore, this issue is obsolete.
