### ISSUE TITLE
Include longitude and latitude in advertising origin/cache

### ISSUE THREAD

**Issue by haoming29** [PelicanPlatform/pelican#464]
In #458, we found that Long/Lat fields of serverAds are empty for Pelican Origins.

For now, we don't include longitude and latitude when advertise to the director and hence there's no way to do a geolocation sort when we pick a cache (or origin if we have same namespace on different origins). We might want to get this info either from a config value or using IP address look up, or GPS if you want to go fancy.

**Comment by jhiemstrawisc** [comment]
Can you look into this again? I think `RecordAd`, the function we use to populate the ttlcache with server ads, calls an "UpdateLatLong" function as its first step. Because our population of lat/long values relies on a proprietary database (maxmind), we centralize that in the director so we only need to keep track of one API key per director instance instead of relying on each external server to provide information. Geo-location of caches does currently work.

**Comment by haoming29** [comment]
Interesting. I tried yesterday with my local director and origin but my origin only shows up in director with 0 for both longitude and latitude. I will take a closer look today and see what’s going on. Thanks for pointing out!
________________________________

**Comment by jhiemstrawisc** [comment]
Ah, that's likely because `UpdateLatLong` does hostname resolution for determining a GeoIP location. Unless the hostname you're using to register an origin or a cache has an actual A Record in DNS, or you've convinced the folks at MaxMind to add the hostname to their database, we default to the null lat/long. One of the 7.4 items I'm working on in the background is providing an override mechanism so that the Director can direct specific namespaces to specific caches.

**Comment by haoming29** [comment]
Close this issue as this is the expected behavior for a container hostname. Other related issues can be a separate ticket.
