### ISSUE TITLE
Have stash_plugin produce valid ClassAd output in more cases

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#511]
Review the stash_plugin to ensure we produce a ClassAd output in as many cases as possible -- or at least a readily identifiable exit code.

For example - if the disk is full, then the writing of the output file will cause a panic, resulting in a fairly generic exit code 2 (the same exit code used for all panics).  Can we assign this a new code?

If the configuration fails to initialize, we do an exit code of 1 -- can we instead write out a failure?

**Comment by joereuss12** [comment]
@bbockelm It's been a while since we discussed this issue, just want to clarify some things. I have a recovery function in place that writes out the classad output file and should catch panics. The questions I have are:

- Do you want me to go through all the common errors we catch from panics and give each one a unique error code?
- Should I modify all the current `exit(1)`'s within `cmd/plugin.go` to have unique codes as well?
- Should I document what each unique code is somewhere?

I'll let you know if any more questions arise.
