### ISSUE TITLE
Expand error reporting from Pelican plugin to the the condor_starter

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#537]
The HTCSS dev team is [expanding the data that can be sent from the plugin](https://opensciencegrid.atlassian.net/browse/HTCONDOR-2122).

We should start filling in the data as part of our plugin outputs.  See [this document](https://docs.google.com/document/d/1jN5FTFwhCD9tAHru0ERxRXWwmF3WdtZy8KuF8pOJA5I/edit) for example of the proposed schema.

There's the idea of "Condor error number" versus "Pelican error number".  The condor error number isn't defined yet so skip that.  The Pelican error number is going to require engineering in a separate issue.  So, for first pass, let's skip those attributes.

**Comment by joereuss12** [comment]
@bbockelm after some discussion with Todd M, it turns out that previous document is outdated and here is the updated one (specifically look under `syntax`): 
https://docs.google.com/document/d/1Gbb7XDOtmLX_xcfmCwP8KAZ_s6PDDGgCamGoDl145Ww/edit

Some things he mentioned that is worth highlighting from our discussion:
- There is now a classad list of classads defined as `TransferErrorData` which contains a list of classad fields that the plugin should start sending out, I can begin progress on this right away.
- A particular classad within `TransferErrorData` is called `IntermediateServer*` attributes, which could provide information if something happens when contacting a server that is not the one specified by the `url` classad
- There is also a classad attribute introduced called `DeveloperData` which can send back whatever classad attributes we would like, condor just sends whatever is inside that attribute and does not check types or anything against it, it is just sent back with the classad outfile.
- Within this `TransferErrorData` with multiple transfers, they will be listed in the order they were tried instead of numbering them within the error.
