### ISSUE TITLE
Single service endpoint offered multiple options

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#557]
After going to the web interface, I get this:

<img width="814" alt="image" src="https://github.com/PelicanPlatform/pelican/assets/1093447/ceef9cfd-5b37-4e23-b447-8f22d5521703">

However, I started this endpoint up with `pelican namespace serve` -- there's only one possible valid answer!

Before showing this splash screen, query the server for its currently-enabled modes and only show the relevant options.

**Comment by haoming29** [comment]
Yes! The original plan was to wait for #503 to be merged first so that we have the variable to look up for the server page to route to. 

To proceed, the assumption for now (putting federation-in-a-box mode aside) is that each process should run only one Pelican server, so we can actually skip this option page and directly route the user to the page of current running server (as each server is supposed to be running at a different port)

Once in the future we polish the "federation-in-a-box" mode and only open one port for all Web UI stuff, we can then revisit this logic and adding back the option page to allow users to jump between different server pages in a single endpoint.

Does this sound right for you? @bbockelm
