### ISSUE TITLE
Version compatibility break for origins

### ISSUE THREAD

**Issue by bbockelm** [PelicanPlatform/pelican#566]
In the work for v7.4.0, we added a new "v2.0" API for the registry.

However, this introduced a compatibility break -- the origin may be registering with an older registry that does not have the v2.0 API.

The origin should either auto-detect the supported API version or gracefully fall back to v1.0 if it gets a 404.

To reproduce, simply run:

```
pelican origin serve -f osg-htc.org -v /tmp/test:/test
```

**Comment by haoming29** [comment]
As discussed with @bbockelm, we should be cautious about introducing a new API version and resist doing it unless we have to break backward compatibility. In this case, adding the new `metadata` prefix is why we upgraded the API version but it seems unnecessary and did cause a backward compatibility issue with the OSDF director and the older version of Pelican, so we decided to roll back this new API version for the registry.

However, after some investigation and browsing through the [PR](https://github.com/PelicanPlatform/pelican/pull/462) that introduced the change, I found that the motivation to add `metadata` to our wildcard router handler (from `/*wildcard` to `/metadata/*wildcard`) is to accommodate new `/getnamespace` API. This is because `gin` doesn't allow a wildcard route present with an exact-match route that shares the same prefix , as a [design choice](https://github.com/julienschmidt/httprouter/issues/73) inherited from the original [httprouter](https://github.com/julienschmidt/httprouter) gin uses: 

```go
router.GET("/getnamesapce", handler1) 
router.GET("/*wildcard", handler2) // This will result in duplicated handler error
```

To rollback to original API routes without losing the new `/getnamespace` handler, I will do what the author of httprouter [suggests](https://github.com/julienschmidt/httprouter/issues/73#issuecomment-90641109),  which is to use middleware to handle the wildcard matching, freeing up router registrations under `/api/v1.0/registry`.
