### ISSUE TITLE
Improvements to the Registry Homepage

### ISSUE THREAD

**Issue by CannonLock** [PelicanPlatform/pelican#632]
Pulled from https://github.com/PelicanPlatform/pelican/issues/558 for 7.5 release.

1. An intro paragraph or sentence about what the registry is and does.
2. Be able to sort and filter on the table contents.
3. Tooltips on the drop down content describing what the column means.
4. Add Standard 'None' for missing data in namespace
5. Add health widget for user == 'admin'

**Comment by CannonLock** [comment]
@haoming29 Added you for the filter, sort api

**Comment by haoming29** [comment]
@CannonLock I've added support for filter against registration fields in #606 but sorting and pagination is still under the way. I'd recommend we using front-end sorting for now and I'll try to spot a good pagination/filter/sort package to use so that we don't have to write a ton of code for doing this.

**Comment by haoming29** [comment]
Honestly, I'm not really sure. I'd use the # of namespaces currently in OSDF as a gauge. @jhiemstrawisc Do you have a better clue?

**Comment by jhiemstrawisc** [comment]
1000 seems pretty large. I suspect we're quite away from needing to really contend with that kind of scaling, by which time most of the underlying code will be different anyway.

**Comment by haoming29** [comment]
@CannonLock Are we planning to tackle this in 7.6? Any blockers that I can help?
