### ISSUE TITLE
Namespace To Do: Implement Auto Discovery

### ISSUE THREAD

**Issue by joereuss12** [PelicanPlatform/pelican#9]
As discussed in the weekly Pelican meeting, we need to implement a way for the namespace to automatically discover registered public keys.

**Comment by bbockelm** [comment]
@jhiemstrawisc - I think this is 90% done.  I think, once #30 is merged, we just need to do end-to-end testing with the director and an origin.

For example, last I tested this functionality, the JWKS public key fetching code in the origin didn't like the public key JWKS that the namespace client was generating (it was missing at least `kty` if not other metadata).  So, finishing off the item is likely just finding all the remaining small bugs in the end-to-end testing.

**Comment by bbockelm** [comment]
@jhiemstrawisc -- we're down to this one last issue for 7.0.0.  How's the end-to-end testing going?

**Comment by jhiemstrawisc** [comment]
I got to this yesterday afternoon and encountered two issues:

1. I can't get the origin to run. When I do `osdf origin serve -v /test:/jhiemstra/test --config /etc/pelican/pelican.yaml -d`, the origin crashes with a note `Error: xrootd process failed unexpectedly: exit status 1`. Sometimes it's CMSD that fails. Going through the output, it looks like TLS initialization is the culprit, even though I have my pelican config pointed to `tls.crt` and `tls.key` that were auto-generated in `/etc/pelican/certificates`.
2. Because we wound up having to break out the Director into a cache and an origin endpoint, we need a way to advertise to both. I don't think the current origin will do that (although because of 1 I haven't been able to test or start fixing).

**Comment by jhiemstrawisc** [comment]
See PR #121. Awaiting review and a few last cleanup items that need input.
